### ISSUE TITLE
Package not working on python3

### ISSUE THREAD

**Issue by rupsabasu2020** [0todd0000/rft1d#4]
Hi!

Is this package only suitable for python2? 

On python3, the package yields the following error on "import rft1d":Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rupsabasu/Library/Python/3.8/lib/python/site-packages/rft1d/__init__.py", line 4, in <module>
    import data, distributions, geom, prob, random
ModuleNotFoundError: No module named 'data'

**Comment by 0todd0000** [comment]
Yes, Python 2 only. This repository is a snapshot for a paper release, and no longer in development.

A Python 3 version is available in [spm1d](https://github.com/0todd0000/spm1d). It can be imported as follows:

```python
from spm1d import rft1d
```

**Comment by rupsabasu2020** [comment]
Thanks a lot for your explanation! I work with the version in spm1d now and it works perfectly.

**Comment by larsgeb** [comment]
Hi Todd, would it be okay if I keep this repo updated for Python 3 using my fork? the spm1d package seems nice, but rft1d is adequate for me.

If so, it would be nice if I could upload the version '0.2' to PyPi, i.e. I need some permissions!

**Comment by 0todd0000** [comment]
Sorry for the delay!  If you are willing to help with maintenance then I'd be happy to keep this going.  What permissions would you like?

Also, since there is already a working Python 3 version in spm1d, I suggest that I port it back to this repository as a starting point. Does that sound OK?

**Comment by larsgeb** [comment]
No worries, I'm in no rush. The main permission is PyPi access to rft1d! I think at the moment only you can push new distributions. It being the first way people try to install software, it would be nice to upload the Python 3 version on there as well.

Sounds good about the point back!

**Comment by 0todd0000** [comment]
Hello, sorry for the very long delay!  I've finally gotten around to updating rft1d for Python 3. There is now better pypi support as well. Please install the new version using:

```
pip install rft1d
```

The PYPI site is:
https://pypi.org/project/rft1d/
